package com.meixxi.zplbox.controller.v1.model;

import org.springframework.http.HttpStatus;

/**
 * Model object for problem details according to RFC 7807 (https://tools.ietf.org/html/rfc7807).
 */
public class ProblemDetails {

    private final int status;
    private final String title;
    private final String type;
    private final String detail;

    /**
     * Custom constructor. Accepting a http status as well as human readable details for initializing.
     */
    public ProblemDetails(HttpStatus httpStatus, String type, String details) {
        this.status = httpStatus.value();
        this.title = httpStatus.getReasonPhrase();
        this.type = type;
        this.detail = details;
    }

    /**
     * The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
     */
    public int getStatus() {
        return status;
    }

    /**
     * A short, human-readable summary of the problem type.
     */
    public String getTitle() {
        return title;
    }

    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    public String getDetail() {
        return detail;
    }

    /**
     * A URI reference [RFC3986] that identifies the problem type.
     */
    public String getType() {
        return type;
    }
}

