
---
stages:
  - validate
  - build
  - deploy
  - destroy




# The OpenTofu component that handles validation, planning, and applying
include:
  - component: $CI_SERVER_FQDN/components/opentofu/validate-plan-apply@2.13.0
    inputs:
      opentofu_version: 1.10.3
      root_dir: 'iac/'
      state_name: 'cloud-run'
      apply_rules:
        - if: '$CI_COMMIT_BRANCH == "main"'
          when: on_success

variables:
  TF_VAR_gcp_project_id: "zplbox-com" # CHANGE THIS
  TF_VAR_gcp_region: "europe-west1"         # CHANGE THIS
  TF_VAR_service_name: "zplbox" # CHANGE THIS
  TF_VAR_gitlab_image_name: "europe-west1-docker.pkg.dev/zplbox-com/gitlab-images/ricebean.net/zplbox/zplbox:1.0.4"
  GOOGLE_APPLICATION_CREDENTIALS: "$GOOGLE_APPLICATION_CREDENTIALS_JSON"

#variables:
#  GITLAB_REPO: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}
#  PROJECT_NAME: ${CI_PROJECT_NAME}
#  VERSION: 1.0.${CI_PIPELINE_IID}
#
#.build:
#  image: docker:20.10.16 # Use a Docker-in-Docker image
#  services:
#    - docker:20.10.16-dind # The Docker daemon
#  script:
#    - >
#      docker build
#      --tag ${GITLAB_REPO}/${PROJECT_NAME}:${VERSION}
#      --build-arg VERSION=${VERSION}
#      --build-arg COMMIT_SHA=${CI_COMMIT_SHA}
#      --build-arg COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA}
#      --build-arg PIPELINE_ID=${CI_PIPELINE_ID}
#      --build-arg PIPELINE_IID=${CI_PIPELINE_IID}
#      --build-arg USER_NAME=${GITLAB_USER_LOGIN}
#      .
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD ${GITLAB_REPO}
#    - docker push ${GITLAB_REPO}/${PROJECT_NAME}:${VERSION}

destroy:
  stage: destroy
  image:
    name: registry.gitlab.com/components/opentofu/gitlab-opentofu:1.10.3-1 # You must specify the OpenTofu image
  when: manual # IMPORTANT: This makes the job a manual trigger
  script:
    - cd $CI_PROJECT_DIR/iac/
    - opentofu init
    - opentofu destroy -auto-approve
  dependencies:
    - apply # This ensures the job has access to the state file from the apply job
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'