
---
stages:
  - validate
  - build
  - deploy

#variables:
#  GITLAB_REPO: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}
#  PROJECT_NAME: ${CI_PROJECT_NAME}
#  VERSION: 1.0.${CI_PIPELINE_IID}
#
#.build:
#  image: docker:20.10.16 # Use a Docker-in-Docker image
#  services:
#    - docker:20.10.16-dind # The Docker daemon
#  script:
#    - >
#      docker build
#      --tag ${GITLAB_REPO}/${PROJECT_NAME}:${VERSION}
#      --build-arg VERSION=${VERSION}
#      --build-arg COMMIT_SHA=${CI_COMMIT_SHA}
#      --build-arg COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA}
#      --build-arg PIPELINE_ID=${CI_PIPELINE_ID}
#      --build-arg PIPELINE_IID=${CI_PIPELINE_IID}
#      --build-arg USER_NAME=${GITLAB_USER_LOGIN}
#      .
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD ${GITLAB_REPO}
#    - docker push ${GITLAB_REPO}/${PROJECT_NAME}:${VERSION}



# The OpenTofu component that handles validation, planning, and applying
include:
  - component: $CI_SERVER_FQDN/components/opentofu/validate-plan-apply@2.13.0
    inputs:
      opentofu_version: 1.10.3

      # Tell the component where to find your Terraform/OpenTofu files
      root_dir: 'iac/'

      # Tell the component which GitLab state to use
      state_name: 'cloud-run' # This can be anything, but it's good practice to name it

      # Pass your variables to the component
#      variables:
#        gcp_project_id: "zplbox-com" # CHANGE THIS
#        gcp_region: "europe-west1"         # CHANGE THIS
#        service_name: "zplbox" # CHANGE THIS
#        gitlab_image_name: "registry.gitlab.com/ricebean.net/zplbox/zplbox:1.0.4"
#        gitlab_image_name: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"

      # Define the rules for when the 'apply' job should run
      apply_rules:
        - if: '$CI_COMMIT_BRANCH == "main"'
          when: on_success

      # The component also has default rules for the 'validate' and 'plan' jobs,
      # which typically run on all branches.

variables:
  # The component automatically forwards any variable prefixed with `TF_VAR_`
  TF_VAR_gcp_project_id: "zplbox-com" # CHANGE THIS
  TF_VAR_gcp_region: "europe-west1"         # CHANGE THIS
  TF_VAR_service_name: "zplbox" # CHANGE THIS
  TF_VAR_gitlab_image_name: "registry.gitlab.com/ricebean.net/zplbox/zplbox:1.0.4"
#  TF_VAR_gitlab_image_name: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"

  # The GCP service account key is a masked variable and does not need a TF_VAR_ prefix
  # The `gitlab-tofu` wrapper script automatically handles this.
  GCP_SA_KEY_JSON: $GCP_SA_KEY_JSON_CONTENT # This is your masked CI/CD variable

# build (test & production)
#test-build:
#  extends: .build
#  stage: build
#  rules:
#    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != 'merge_request_event'
#  before_script:
#    - VERSION=${VERSION}-dev
#
#prod-build:
#  extends: .build
#  stage: build
#  rules:
#    - if: $CI_COMMIT_BRANCH == "main"

# The Terraform deployment stage
#deploy-to-gcp:
#  stage: deploy
#  image:
#    name: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
#    entrypoint:
#      - /usr/bin/env
#      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
#  variables:
#    # Set the backend to use GCS for state management
#    TF_VAR_gcp_project_id: "zplbox-com" # CHANGE THIS
#    TF_VAR_gcp_region: "europe-west1"         # CHANGE THIS
#    TF_VAR_service_name: "zplbox" # CHANGE THIS
#    TF_VAR_gitlab_image_name: "registry.gitlab.com/ricebean.net/zplbox/zplbox:1.0.4"
##    TF_VAR_gitlab_image_name: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
#  script:
#    - cd iac
#    - terraform init
#    - terraform validate
#    - terraform plan -out=tfplan
#    - terraform apply -auto-approve tfplan
#  rules:
#    - if: '$CI_COMMIT_BRANCH == "main"'
