openapi: 3.0.3
info:
  title: ZplBox
  description: |-
    Conversion of content into ZPL.
  version: 1.0.0
servers:
  - url: http://localhost:8080/
tags:
  - name: html2zpl
    description: Conversion of HTML based web content to ZPL.
  - name: pdf2zpl
    description: Conversion of PDF Documents to ZPL.
  - name: System
    description: System Endpoint.
paths:
  /v1/html2zpl:
    post:
      tags:
        - html2zpl
      summary: Conversion of Web Content to ZPL.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HtmlRenderingParams'
      responses:
        '200':
          $ref: "#/components/responses/ZplLabelResponse"
        '400':
          $ref: '#/components/responses/BadRequest'

  /v1/html2zpl/render:
    post:
      tags:
        - html2zpl
      summary: Rendering of web content to a colored PNG.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HtmlRenderingParams'
      responses:
        '200':
          description: The rendered PNG image.
          content:
              application/png:
                schema: 
                  type: string
                  format: binary
        '400':
          $ref: '#/components/responses/BadRequest'

  /v1/pdf2zpl:
    post:
      tags:
        - pdf2zpl
      summary: Conversion of PDF Documents to ZPL.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PdfRenderingParams'
      responses:
        '200':
          $ref: "#/components/responses/ZplLabelResponse"
        '400':
          $ref: '#/components/responses/BadRequest'

  /version:
    get:
      tags:
        - System
      summary: Version details.
      responses:
        '200':
          description: Version details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Version"

  /status:
    get:
      tags:
        - System
      summary: Status details.
      responses:
        '200':
          description: Status details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Status"

components:
  responses:
    ZplLabelResponse:
      description: The ZPL Label
      content:
        text/plain:
          schema:
            $ref: '#/components/schemas/ZplLabel'
    BadRequest:
      description: The request could not be understood by the server due to malformed syntax.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
    NoContent:
      description: No content.

  schemas:
    HtmlRenderingParams:
      type: object
      required: [widthPts, heightPts]
      properties:
        url:
          type: string
          description: The url of the web content to be rendered (conditional). If set, dataBase64 SHALL be undefined.
          example: http://localhost:8080/labels/test-label-1.html
        dataBase64:
          type: string
          description: The Base64 encoded html file (conditional). If set, url SHALL be undefined.
          example: PCFkb2N0eXBlIGh0bWw+CjxodG1sIGxhbmc...
        widthPts:
          type: integer
          description: The target rendered width of the ZPL label in points.
          example: 600
        heightPts:
          type: integer
          description: The target rendered width of the ZPL label in points.
          example: 800

    PdfRenderingParams:
      type: object
      required: [dotsPerInch]
      properties:
        url:
          type: string
          description: The url of the web content to be rendered (conditional). If set, dataBase64 SHALL be undefined.
          example: http://localhost:8080/labels/test-label-1.html
        dataBase64:
          type: string
          description: The Base64 encoded html file (conditional). If set, url SHALL be undefined.
          example: PCFkb2N0eXBlIGh0bWw+CjxodG1sIGxhbmc...
        dotsPerInch:
          type: integer
          description: Resolution in dots per inch (dpi).
          example: 203

    ProblemDetails:
      type: object
      properties:
        status:
          type: integer
          example: 400
        title:
          type: string
          example: Unsupported Operation
        type:
          type: string
          example: type
        detail:
          type: string
          example: some more details

    Version:
      type: object
      properties:
        appName:
          type: string
          example: html2zpl
        appVersion:
          type: string
          example: 1.0.1
        commitId:
          type: string
          example: c51cc22b4873d280f95b4eff63bbfbdec431f42f

    Status:
      type: object
      properties:
        status:
          type: string
          description: Is always 'UP'.
          example: UP
        startTime:
          type: integer
          description: The service's start time in epoch millis
          example: 1724108519253
        startTimeReadable:
          type: string
          description: The start time in a human-readable format
          example: 2024-08-20T01:01:59.253+02:00[Europe/Berlin]
        duration:
          type: integer
          description: Relative start time in epoch millis
          example: 10100
        durationReadable:
          type: string
          description: Relative start time in a human-readable format
          example: 00h 00m 10s
        hostname:
          type: string
          description: The hosts name.
          example: host01
        version:
          $ref: "#/components/schemas/Version"

    ZplLabel:
      type: string
      example: |
        ^XA 
        ^FO0,0^GFA,60000,60000,75,FFF8C000180000003...
        ^XZ

        

