app:
  name: ZplBox
  version: ${version}
  buildtime: ${buildtime}


spring:
  profiles:
    active: community
  main:
    banner-mode: off

---
# Community Profiles
spring:
  config:
    activate:
      on-profile: community

app:
  edition: Community

---
# RapidAPI Profiles
spring:
  config:
    activate:
      on-profile: rapidapi

app:
  edition: Cloud

rapidapi:
  secret: secret