app:
  name: @appname@
  version: @version@
  buildtime: @buildtime@


spring:
  main:
    banner-mode: off
  mandatory-file-encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
  security:
    user:
      name: n.a.
      password: n.a.
