app:
  name: ZplBox
  version: ${version}
  buildtime: ${buildtime}


spring:
  profiles:
    active: rapidapi
  main:
    banner-mode: off

---
# Community Profiles
spring:
  config:
    activate:
      on-profile: community

---
# RapidAPI Profiles
spring:
  config:
    activate:
      on-profile: rapidapi

rapidapi:
  secret: secret