name: Build and Publish ZplBox Image on Tag

on:
  push:
    tags:
      - 'v*' # Triggers on tags like v1.0, v1.2.3, etc.
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ricebean-net/zplbox

jobs:
  deploy-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |-
          docker build \
            -t "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" \
            -t "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{env.VERSION}}" \
            --build-arg VERSION=${{env.VERSION}} \
            --build-arg COMMIT_SHA=${GITHUB_SHA} \
            .

      - name: Publish Docker Image to github
        run: |
          docker push "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
          docker push "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{env.VERSION}}"
